# Generated by Django 4.2.7 on 2024-01-31 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Image', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
