# Generated by Django 4.2.7 on 2024-02-01 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='Category',
            field=models.CharField(default=datetime.datetime(2024, 2, 1, 10, 9, 1, 24054, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
    ]
